export const backendStacks = [
    "Node.js",
    "Express.js",
    "Django",
    "Ruby on Rails",
    "Java",
    "Spring Boot",
    "Flask",
    "Laravel",
    "ASP.NET Core",
    "FastAPI",
    "Go (Golang)",
    "NestJS",
    "Koa.js",
    "Hapi.js",
    "Sails.js",
    "Phoenix (Elixir)",
    "Rails API",
    "Python",
    "C#",
    "PHP",
    "Scala",
    "Elixir",
    "Clojure",
    "Rust",
    "GraphQL",
    "Apollo Server",
    "Firebase (Serverless)",
    "AWS Lambda",
    "Serverless Framework",
    "Cloud Functions (Google Cloud, AWS)",
    "Docker",
    "Kubernetes",
    "Nginx",
    "Apache",
    "RabbitMQ",
    "Kafka",
    "Redis",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "SQLite",
    "CouchDB",
    "Elasticsearch",
    "Mongoose",
    "Prisma",
    "TypeORM",
    "Sequelize",
    "Knex.js",
    "JWT (JSON Web Tokens)",
    "OAuth 2.0",
    "Passport.js",
    "AWS API Gateway",
    "Google Cloud Functions",
    "Azure Functions",
    "Stripe (for Payments)",
    "Twilio (for Messaging)",
    "SendGrid (for Emails)",
    "Elastic Beanstalk",
    "Heroku",
    "Vercel (Backend)",
    "Firebase Firestore",
    "Redis",
    "Socket.io",
    "WebSockets",
    "GraphQL Subscriptions",
    "JUnit",
    "Mockito",
    "Postman",
    "Swagger",
    "OpenAPI",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitLab CI",
    "Terraform",
    "Ansible",
    "Chef",
    "Puppet",
    "RabbitMQ",
    "Apache Kafka",
    "Prometheus",
    "Grafana"
];
