export const frontendStacks = [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Vue.js",
    "Angular",
    "Svelte",
    "Next.js",
    "Gatsby",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Foundation",
    "Bulma",
    "Ant Design",
    "Styled Components",
    "CSS Grid",
    "Flexbox",
    "jQuery",
    "Ember.js",
    "Preact",
    "Pug",
    "Sass",
    "Less",
    "PostCSS",
    "Webpack",
    "Babel",
    "ESLint",
    "Parcel",
    "Vite",
    "React Native",
    "Expo",
    "Electron",
    "Framer Motion",
    "GSAP",
    "Chart.js",
    "D3.js",
    "Storybook",
    "Jest",
    "React Testing Library",
    "Cypress",
    "Mocha",
    "Chai",
    "Sinon",
    "Webpack Dev Server",
    "Figma (for design)",
    "Sketch (for design)",
    "Adobe XD (for design)",
    "Framer (for design)",
    "Tailwind UI",
    "Lottie",
    "Markdown",
    "GraphQL",
    "Apollo Client",
    "Redux",
    "Redux Toolkit",
    "React Query",
    "React Router",
    "NextAuth.js",
    "Prisma",
    "Firebase",
    "Supabase",
    "Sanity.io",
    "Contentful",
    "Netlify",
    "Vercel",
    "Cloudinary",
    "Strapi",
    "Headless CMS",
    "PWA (Progressive Web App)"
];
